version: "3.3"
networks:
  app-tier:
    driver: bridge

services:
  app:
    image: laravel-www
    container_name: laravel-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mysql
      - consul
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    ports:
      - 8080:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app

  redis:
    container_name: laravel-redis
    image: redis:4-alpine
    networks:
      - app-tier
    ports:
      - 16379:6379
    volumes:
      - ./data/redis:/data

  mysql:
    container_name: laravel-mysql
    image: mysql:5.7
    networks:
      - app-tier
    ports:
      - 13306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  consul:
    image: consul:1.6.2
    volumes:
      - ./data/consul:/consul/data
    networks:
      - app-tier
    ports:
      - 8500:8500
